app:
    resource: "@Storefront/Controller/"
    type:     annotation

api_product:
    resource: "@Product/Resources/config/routing.yml"
    prefix:   "/api"

nexus:
    resource: "@Nexus/Controller/"
    type:     annotation
